# Generated by Django 5.1.2 on 2024-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
