# Generated by Django 5.1.2 on 2024-10-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_texto_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
